image: node:20

variables:
  GIT_DEPTH: 0

stages:
  - build
  - test

.common:
  stage: build
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
      - .nx
  before_script:
    - npm ci --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

build:
  stage: build
  extends: .common
  script:
    - npx nx affected --verbose --base=$NX_BASE --head=$NX_HEAD -t lint build --parallel=3

test:
  stage: test
  extends: .common
  script:
    - npx nx affected --verbose --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3